# -*- coding: utf-8 -*-
"""TwinEdge_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypfOXlpVWpzaO00akC9W3RBaEzLNoCRj

# TwinEdge AI: Edge-Based Digital Twin for Predictive Maintenance and Smart Manufacturing

## Project Objective

The objective of this project is to develop an AI-powered predictive maintenance system that can identify potential machine failures before they occur. By analyzing machine sensor data such as temperature, rotational speed, torque, and tool wear, the system predicts equipment health and helps reduce unplanned downtime.

TwinEdge AI combines Machine Learning, Edge AI concepts, and Digital Twin principles to support smart manufacturing environments. The solution aims to improve operational efficiency, reduce maintenance costs, and enhance equipment reliability.

# Dataset Overview

This project uses the AI4I 2020 Predictive Maintenance Dataset.

The dataset contains information collected from industrial machines, including:

- Air Temperature [K]
- Process Temperature [K]
- Rotational Speed [rpm]
- Torque [Nm]
- Tool Wear [min]

The dataset also includes different failure modes:

- TWF (Tool Wear Failure)
- HDF (Heat Dissipation Failure)
- PWF (Power Failure)
- OSF (Overstrain Failure)
- RNF (Random Failure)

Target Variable:
- Machine Failure (0 = Healthy, 1 = Failure)

The dataset is used to train a Machine Learning model that predicts machine failures based on sensor readings and operational conditions.

Install Libraries
"""

pip install pandas numpy matplotlib seaborn scikit-learn joblib

"""Import Liraries

"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

import joblib

"""Load Dataset

"""

df = pd.read_csv("/content/TwinEdge_AI (ai4i2020).csv")

df.head()

"""Check Dataset

"""

df.info()

df.describe()

df.isnull().sum()

"""Exploratory DAta ANALYSIS

"""

sns.countplot(x='Machine failure', data=df)

plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(df.corr(numeric_only=True),
            annot=True)

plt.show()

"""Data Preparation

"""

df.columns

X = df.drop(
    ['UDI',
     'Product ID',
     'Type',
     'Machine failure'],
    axis=1
)

y = df['Machine failure']

"""Train-Test Split

"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

"""Train the Random Forest Model"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

print("Model Training Completed")

"""Make Prediction

"""

y_pred = rf_model.predict(X_test)

print(y_pred[:10])

""" Check Model Accuracy"""

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

"""Generate Classification Report"""

print(classification_report(y_test, y_pred))

"""Feature Important Graph"""

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

plt.figure(figsize=(10,6))

sns.barplot(
    x='Importance',
    y='Feature',
    data=feature_importance
)

plt.title("Feature Importance")
plt.show()

"""Save the Model"""

import os
os.makedirs("models", exist_ok=True)

joblib.dump(rf_model, "models/predictive_maintenance_model.pkl")
print("Model Saved Successfully")

import  os
os.listdir("models")

"""Test the Saved Model

"""

loaded_model = joblib.load(
    "models/predictive_maintenance_model.pkl"
)

sample_prediction = loaded_model.predict(
    X_test.iloc[:1]
)

print(sample_prediction)

"""Project Conclusion Cell

# Conclusion

TwinEdge AI successfully predicts potential machine failures
using machine sensor data.

The model can be integrated with Edge AI devices and a
Digital Twin dashboard to support predictive maintenance
in smart manufacturing environments.

Benefits:
- Reduced downtime
- Lower maintenance costs
- Improved machine health monitoring
- Industry 4.0 readiness

TwinEdge AI Dashboard

Dashboard
"""

import pandas as pd

dashboard = pd.DataFrame({
    "Metric": [
        "Model Accuracy",
        "Machine Status",
        "Top Failure Factor",
        "Prediction Model"
    ],
    "Value": [
        "99.9%",
        "Healthy",
        "HDF",
        "Random Forest"
    ]
})

dashboard

"""Machine Health Gauge"""

import matplotlib.pyplot as plt

health_score = 99.9

plt.figure(figsize=(8,3))
plt.barh(["Machine Health"], [health_score])
plt.xlim(0,100)
plt.title("TwinEdge AI - Machine Health Score")
plt.show()

"""Failure Risk Dashboard"""

risk_data = {
    "HDF":0.31,
    "OSF":0.22,
    "PWF":0.19,
    "TWF":0.11
}

plt.figure(figsize=(8,4))
plt.bar(risk_data.keys(), risk_data.values())
plt.title("Failure Risk Factors")
plt.ylabel("Importance")
plt.show()

"""TwinEdge AI Summary Dashboard"""

print("="*50)
print("          TwinEdge AI Dashboard")
print("="*50)
print("Machine Status      : Healthy")
print("Model Accuracy      : 99.9%")
print("Prediction Engine   : Random Forest")
print("Top Risk Factor     : HDF")
print("Maintenance Advice  : Continue Monitoring")
print("="*50)

!pip install plotly

import plotly.express as px

fig = px.bar(
    feature_importance,
    x="Importance",
    y="Feature",
    orientation="h",
    title="TwinEdge AI Feature Importance Dashboard"
)

fig.show()

"""# Future Scope

- Deploy the model on Edge AI devices such as Raspberry Pi or NVIDIA Jetson Nano.
- Integrate real-time IoT sensors for live machine monitoring.
- Develop a full Digital Twin visualization system.
- Implement automated maintenance alerts.
- Extend the solution for multiple industrial machines and production lines.
- Integrate cloud analytics for large-scale manufacturing environments.

# Thank You

TwinEdge AI demonstrates how Machine Learning and Edge AI can be used for predictive maintenance in smart manufacturing environments.

Model Accuracy Achieved: 99.9%

This solution can be further extended into a real-time Digital Twin platform integrated with IoT sensors and Edge Computing devices.
"""